Repository Pironeer-APP/Pironeer_Homework_Web, pull requests merged in 2024-11, with the labels that each got.

#10 feat: 회원(관리자) delete 메서드 추가
  src/main/java/prioneer/homework/member/repository/MemberRepository.java
  src/main/java/prioneer/homework/member/web/admin/join/SystemJoinController.java
Labels: feat

#13 feat: SystemJoinController, UserNewController, MasterListController 구현, Member 엔티티 필드 타입 변경
  src/main/java/prioneer/homework/member/domain/Member.java
  src/main/java/prioneer/homework/member/repository/MemberRepository.java
  src/main/java/prioneer/homework/member/web/admin/join/SystemJoinController.java
  src/main/java/prioneer/homework/member/web/admin/system/MasterListController.java
  src/main/java/prioneer/homework/member/web/admin/system/SystemListController.java
  src/main/java/prioneer/homework/member/web/admin/system/UserNewController.java
  src/main/resources/application.properties
Labels: refactor, feat

#16 feat: 홈 컨트롤러 로직 만듬 로그인 됐을때 안됐을때
  src/main/java/prioneer/homework/home/web/HomeController.java
Labels: feat

#17 feat: 일반 유저들 과제 확인 페이지 로직 만듬
  src/main/java/prioneer/homework/board/repository/HomeworkRepository.java
  src/main/java/prioneer/homework/board/web/user/UserHomeworkController.java
Labels: feat

#19 feat: AdminHomeworkController 구현
  src/main/java/prioneer/homework/board/repository/HomeworkRepository.java
  src/main/java/prioneer/homework/board/web/admin/AdminHomeworkController.java
  src/main/java/prioneer/homework/board/web/user/UserHomeworkController.java
  src/main/java/prioneer/homework/member/repository/MemberRepository.java
  src/main/java/prioneer/homework/member/service/user/UserMemberService.java
  src/main/java/prioneer/homework/member/web/user/login/UserLoginController.java
Labels: feat

#27 refactor: memberId 필드 타입 수정, @RequestParam 모두 삭제
  src/main/java/prioneer/homework/board/repository/HomeworkRepository.java
  src/main/java/prioneer/homework/board/service/admin/AdminBoardService.java
  src/main/java/prioneer/homework/board/web/admin/AdminHomeworkController.java
  src/main/java/prioneer/homework/config/data/DataInitializer.java
  src/main/java/prioneer/homework/member/repository/MemberRepository.java
  src/main/java/prioneer/homework/member/service/admin/AdminMemberService.java
  src/main/java/prioneer/homework/member/web/admin/join/SystemJoinController.java
  src/main/java/prioneer/homework/member/web/admin/login/SystemLoginController.java
  src/main/java/prioneer/homework/member/web/admin/system/MasterListController.java
  src/main/java/prioneer/homework/member/web/admin/system/SystemListController.java
  src/main/java/prioneer/homework/member/web/admin/system/UserNewController.java
Labels: refactor

#28 feat: 일반 유저 로그인 템플릿 이었어요
  src/main/java/prioneer/homework/home/web/HomeController.java
  src/main/java/prioneer/homework/member/web/user/login/UserLoginController.java
  src/main/resources/templates/home/home_loginafter.html
  src/main/resources/templates/home/home_loginbefore.html
  src/main/resources/templates/home/login.html
Labels: feat

#29 fix: 유저 과제 레포지토리 체크 표시 수정
  src/main/java/prioneer/homework/board/repository/HomeworkRepository.java
Labels: fix

#30 feat: 신규 회원 추가 될때 과제 18개 추가 및 ROLE 수정
  src/main/java/prioneer/homework/board/repository/HomeworkRepository.java
  src/main/java/prioneer/homework/board/web/user/UserHomeworkController.java
  src/main/java/prioneer/homework/info/repository/InfoRepository.java
  src/main/java/prioneer/homework/member/service/admin/AdminMemberService.java
  src/main/java/prioneer/homework/member/web/admin/login/SystemLoginController.java
Labels: feat

#32 feat: 과제 업데이트 할때 관리자 아이디 실시간 변경 및 html 타임리프 정의 추가
  src/main/java/prioneer/homework/board/repository/HomeworkRepository.java
  src/main/java/prioneer/homework/board/web/admin/AdminHomeworkController.java
  src/main/resources/templates/admin/admin_home_loginbefore.html
  src/main/resources/templates/home/home_loginafter.html
  src/main/resources/templates/home/home_loginbefore.html
  src/main/resources/templates/user/assignment_user.html
Labels: feat

#33 feat: 중간점검
  README.md
  src/main/java/prioneer/homework/board/repository/HomeworkRepository.java
  src/main/java/prioneer/homework/board/service/admin/AdminBoardService.java
  src/main/java/prioneer/homework/board/web/admin/AdminHomeworkController.java
  src/main/java/prioneer/homework/board/web/user/UserHomeworkController.java
  src/main/java/prioneer/homework/config/data/DataInitializer.java
  src/main/java/prioneer/homework/home/web/HomeController.java
  src/main/java/prioneer/homework/info/repository/InfoRepository.java
  src/main/java/prioneer/homework/member/domain/Member.java
  src/main/java/prioneer/homework/member/repository/MemberRepository.java
  src/main/java/prioneer/homework/member/service/admin/AdminMemberService.java
  src/main/java/prioneer/homework/member/service/user/UserMemberService.java
  src/main/java/prioneer/homework/member/web/admin/join/SystemJoinController.java
  src/main/java/prioneer/homework/member/web/admin/login/SystemLoginController.java
  src/main/java/prioneer/homework/member/web/admin/system/MasterListController.java
  src/main/java/prioneer/homework/member/web/admin/system/SystemListController.java
  src/main/java/prioneer/homework/member/web/admin/system/UserNewController.java
  src/main/java/prioneer/homework/member/web/user/login/UserLoginController.java
  src/main/resources/application.properties
  src/main/resources/static/css/admin_home_loginbefore.css
  src/main/resources/static/css/assignment_user.css
  src/main/resources/static/css/home_loginafter.css
  src/main/resources/static/css/home_loginbefore.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/style.css
  src/main/resources/templates/admin/admin_home_loginbefore.html
  src/main/resources/templates/admin/test.html
  src/main/resources/templates/home/home_loginafter.html
  src/main/resources/templates/home/home_loginbefore.html
  src/main/resources/templates/home/login.html
  src/main/resources/templates/home/test.html
  src/main/resources/templates/user/assignment_user.html
  src/main/resources/templates/user/test.html
Labels: feat

#34 fix: 관리자 로그인 회원가입 일부 로직 수정
  src/main/java/prioneer/homework/config/PasswordConfig.java
  src/main/java/prioneer/homework/member/repository/MemberRepository.java
  src/main/java/prioneer/homework/member/web/admin/join/SystemJoinController.java
  src/main/java/prioneer/homework/member/web/admin/login/SystemLoginController.java
Labels: fix

#35 feat: form 태그에 object 붙여서 처리 및 each 반복문 해결
  src/main/resources/static/css/master_manage.css
  src/main/resources/templates/admin/admin_assignment_list.html
  src/main/resources/templates/admin/admin_home_loginafter.html
  src/main/resources/templates/admin/admin_home_loginbefore.html
  src/main/resources/templates/admin/admin_join.html
  src/main/resources/templates/admin/admin_login.html
  src/main/resources/templates/admin/admin_register.html
  src/main/resources/templates/admin/admin_start.html
  src/main/resources/templates/admin/assignment_admin.html
  src/main/resources/templates/admin/master_manage.html
  src/main/resources/templates/admin/master_start.html
Labels: feat

#36 feat: 관리자 권한 로직 및 /system 페이지 생성했어요
  src/main/java/prioneer/homework/config/WebConfig.java
  src/main/java/prioneer/homework/home/web/HomeController.java
  src/main/java/prioneer/homework/member/service/admin/AdminMemberService.java
  src/main/java/prioneer/homework/member/web/admin/system/MasterListController.java
  src/main/java/prioneer/homework/member/web/admin/system/SystemController.java
  src/main/java/prioneer/homework/member/web/admin/system/UserNewController.java
Labels: feat

#37 feat: 관리자 리스트 및 회원리스트 AJAX로 수정 삭제 구현했어요
  src/main/java/prioneer/homework/member/repository/MemberRepository.java
  src/main/java/prioneer/homework/member/service/admin/AdminMemberService.java
  src/main/java/prioneer/homework/member/web/admin/system/MasterListController.java
  src/main/java/prioneer/homework/member/web/admin/system/SystemListController.java
  src/main/resources/templates/admin/admin_assignment_list.html
  src/main/resources/templates/admin/master_manage.html
Labels: feat

#38 feat: 로그인 타임리프 오류 메시지 추가했어요
  src/main/java/prioneer/homework/member/web/user/login/UserLoginController.java
  src/main/resources/templates/admin/admin_assignment_list.html
  src/main/resources/templates/home/login.html
Labels: feat

#39 feat: 22기 부원들 과제 결과 보여주기 만들었어요.
  src/main/java/prioneer/homework/board/repository/HomeworkRepository.java
  src/main/java/prioneer/homework/board/web/user/UserHomeworkController.java
  src/main/java/prioneer/homework/config/data/DataInitializer.java
  src/main/java/prioneer/homework/info/domain/Info.java
  src/main/resources/templates/home/login.html
  src/main/resources/templates/user/assignment_user.html
Labels: feat

#40 feat: 22기 과제 결과 보증금 계산 로직을 구현했고. html 쪽 css 경로 다 수정했어요!
  src/main/java/prioneer/homework/board/domain/Board.java
  src/main/java/prioneer/homework/board/repository/HomeworkRepository.java
  src/main/java/prioneer/homework/board/web/admin/AdminHomeworkController.java
  src/main/java/prioneer/homework/board/web/user/UserHomeworkController.java
  src/main/java/prioneer/homework/home/web/HomeController.java
  src/main/java/prioneer/homework/member/repository/MemberRepository.java
  src/main/java/prioneer/homework/member/service/admin/AdminMemberService.java
  src/main/java/prioneer/homework/member/web/admin/system/MasterListController.java
  src/main/java/prioneer/homework/member/web/admin/system/SystemListController.java
  src/main/java/prioneer/homework/member/web/admin/system/UserNewController.java
  src/main/resources/application.properties
  src/main/resources/templates/admin/admin_assignment_list.html
  src/main/resources/templates/admin/admin_home_loginafter.html
  src/main/resources/templates/admin/admin_home_loginbefore.html
  src/main/resources/templates/admin/admin_join.html
  src/main/resources/templates/admin/admin_login.html
  src/main/resources/templates/admin/admin_register.html
  src/main/resources/templates/admin/admin_start.html
  src/main/resources/templates/admin/assignment_admin.html
  src/main/resources/templates/admin/master_manage.html
  src/main/resources/templates/admin/master_start.html
  src/main/resources/templates/home/home_loginafter.html
  src/main/resources/templates/home/home_loginbefore.html
  src/main/resources/templates/home/login.html
  src/main/resources/templates/user/assignment_user.html
Labels: feat

#41 fix: list 쪽 수정 삭제 js로 오류해결했습니다. 타임리프 오류도 해결했습니다.
  src/main/java/prioneer/homework/board/repository/HomeworkRepository.java
  src/main/java/prioneer/homework/board/web/admin/AdminHomeworkController.java
  src/main/java/prioneer/homework/board/web/user/UserHomeworkController.java
  src/main/java/prioneer/homework/config/data/DataInitializer.java
  src/main/java/prioneer/homework/home/web/HomeController.java
  src/main/java/prioneer/homework/member/repository/MemberRepository.java
  src/main/java/prioneer/homework/member/service/admin/AdminMemberService.java
  src/main/java/prioneer/homework/member/web/admin/login/SystemLoginController.java
  src/main/java/prioneer/homework/member/web/admin/system/MasterListController.java
  src/main/java/prioneer/homework/member/web/admin/system/SystemController.java
  src/main/java/prioneer/homework/member/web/admin/system/SystemListController.java
  src/main/java/prioneer/homework/member/web/admin/system/UserNewController.java
  src/main/java/prioneer/homework/member/web/user/login/UserLoginController.java
  src/main/resources/templates/admin/admin_assignment_list.html
  src/main/resources/templates/admin/admin_join.html
  src/main/resources/templates/admin/admin_login.html
  src/main/resources/templates/admin/admin_register.html
  src/main/resources/templates/admin/assignment_admin.html
  src/main/resources/templates/admin/master_manage.html
  src/main/resources/templates/user/assignment_user.html
Labels: fix

#43 fix: 잔기능 수정했습니다.
  src/main/java/prioneer/homework/member/web/admin/system/UserNewController.java
  src/main/resources/application.properties
  src/main/resources/templates/admin/admin_assignment_list.html
  src/main/resources/templates/admin/admin_home_loginafter.html
  src/main/resources/templates/admin/admin_home_loginbefore.html
  src/main/resources/templates/admin/admin_join.html
  src/main/resources/templates/admin/admin_login.html
  src/main/resources/templates/admin/admin_register.html
  src/main/resources/templates/admin/admin_start.html
  src/main/resources/templates/admin/assignment_admin.html
  src/main/resources/templates/admin/master_manage.html
  src/main/resources/templates/admin/master_start.html
  src/main/resources/templates/home/home_loginafter.html
  src/main/resources/templates/home/home_loginbefore.html
  src/main/resources/templates/home/login.html
  src/main/resources/templates/user/assignment_user.html
Labels: fix

#48 feat: 로그아웃, 폰번호 양식, 회원검색 기능 추가했어요
  src/main/java/prioneer/homework/member/web/user/login/UserLoginController.java
  src/main/resources/static/css/admin_assignment_list.css
  src/main/resources/templates/admin/admin_assignment_list.html
  src/main/resources/templates/admin/admin_home_loginafter.html
  src/main/resources/templates/admin/admin_home_loginbefore.html
  src/main/resources/templates/admin/admin_join.html
  src/main/resources/templates/admin/admin_login.html
  src/main/resources/templates/admin/admin_register.html
  src/main/resources/templates/admin/admin_start.html
  src/main/resources/templates/admin/assignment_admin.html
  src/main/resources/templates/admin/master_manage.html
  src/main/resources/templates/admin/master_start.html
  src/main/resources/templates/error/4xx.html
  src/main/resources/templates/error/5xx.html
  src/main/resources/templates/home/home_loginafter.html
  src/main/resources/templates/home/home_loginbefore.html
  src/main/resources/templates/home/login.html
  src/main/resources/templates/user/assignment_user.html
Labels: feat

#51 feat: 로고 수정
  src/main/resources/static/logo/logo.png
  src/main/resources/templates/admin/admin_assignment_list.html
  src/main/resources/templates/admin/admin_home_loginafter.html
  src/main/resources/templates/admin/admin_home_loginbefore.html
  src/main/resources/templates/admin/admin_join.html
  src/main/resources/templates/admin/admin_login.html
  src/main/resources/templates/admin/admin_register.html
  src/main/resources/templates/admin/admin_start.html
  src/main/resources/templates/admin/assignment_admin.html
  src/main/resources/templates/admin/master_manage.html
  src/main/resources/templates/admin/master_start.html
  src/main/resources/templates/home/home_loginafter.html
  src/main/resources/templates/home/home_loginbefore.html
  src/main/resources/templates/home/login.html
  src/main/resources/templates/user/assignment_user.html
Labels: feat
